heat_template_version: queens

parameters:
  public_net_id:
    type: string
  control_network_cidr:
    type: string
  dns_nameservers:
    type: json
    default: []

resources:

  network:
    type: OS::Neutron::Net
  subnet:
    type: OS::Neutron::Subnet
    properties:
      network: { get_resource: network }
      enable_dhcp: false
      cidr: { get_param: control_network_cidr }
      dns_nameservers: { get_param: dns_nameservers }

  router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info:
        network: { get_param: public_net_id }
  router_iface:
    type: OS::Neutron::RouterInterface
    properties:
      router: { get_resource: router }
      subnet: { get_resource: subnet }


outputs:
  public_network:
    value: { get_resource: network }
  accessible_subnet_id:
    value: { get_resource: subnet }
