apiVersion: lcm.mirantis.com/v1alpha1
kind: OpenStackDeploymentSecret
metadata:
  name: osh-dev
  namespace: openstack
spec:
  features:
    database:
      backup:
        sync:
          conf:
            user_uid: user_s3_backup
            display_name: "User S3 backup"
            access_key: NY23MEG99GR68XDO4IT3
            secret_key: Pc5VMqfAnKIUD7AAXDVEZIW2Hp9sCkFAQkSNnqRh
    ssl:
      public_endpoints:
        api_cert: |-
          # Update server certificate content
        api_key: |-
          # Update server private key content
        ca_cert: |-
          # Update CA certificate content
