apiVersion: lcm.mirantis.com/v1alpha1
kind: OpenStackDeploymentSecret
metadata:
  name: osh-dev
  namespace: openstack
spec:
  features:
#    barbican:
#      backends:
#        vault:
#          approle_role_id: ebbe208d-ce9f-dfe0-c58c-1b6440fec5e6
#          approle_secret_id: 784a5058-3926-e594-d5c8-66292a65015c
    ssl:
      public_endpoints:
        api_cert: |-
          # Update server certificate content
        api_key: |-
          # Update server private key content
        ca_cert: |-
          # Update CA certificate content
