apiVersion: v1
data:
  # http proxy and https proxy - squid.openstack.svc.cluster.local
  HTTP_PROXY: aHR0cDovL3NxdWlkLm9wZW5zdGFjay5zdmMuY2x1c3Rlci5sb2NhbDo4MAo=
  HTTPS_PROXY: aHR0cDovL3NxdWlkLm9wZW5zdGFjay5zdmMuY2x1c3Rlci5sb2NhbDo4MAo=
  # no_proxy - .svc.cluster.local,.it.just.works,10.96.0.1
  NO_PROXY: LnN2Yy5jbHVzdGVyLmxvY2FsLC5pdC5qdXN0LndvcmtzLDEwLjk2LjAuMQo=
kind: Secret
metadata:
  name: cc-proxy
  namespace: osh-system
type: Opaque
