---
apiVersion: lcm.mirantis.com/v1alpha1
kind: HelmBundle
metadata:
  name: squid
  namespace: osh-system
spec:
  releases:
  - chart: lifen/squid
    name: squid
    namespace: openstack
    version: 0.3.0
    helmV3: true
  repositories:
  - name: lifen
    url: https://honestica.github.io/lifen-charts/
