apiVersion: lcm.mirantis.com/v1alpha1
kind: HelmBundle
metadata:
  name: openstack-virtualbmc
  namespace: openstack-vbmc
spec:
  releases:
  - chart: osh-infra/openvswitch
    name: vbmc-openvswitch
    namespace: openstack-vbmc
    values:
      endpoints:
        cluster_domain_suffix: cluster.local
      images:
        tags:
          dep_check: docker-kaas-local.artifactory.mirantis.com/openstack/extra/kubernetes-entrypoint:v1.0.0-20200311160233
          image_repo_sync: docker-kaas-local.artifactory.mirantis.com/openstack/extra/docker:17.07.0
          openvswitch_db_server: docker-kaas-local.artifactory.mirantis.com/general/openvswitch:2.11-bionic-20200409092635
          openvswitch_vswitchd: docker-kaas-local.artifactory.mirantis.com/general/openvswitch:2.11-bionic-20200409092635
      labels:
        ovs:
          node_selector_key: virtualbmc
          node_selector_value: enabled
    version: 0.1.0-mcp-2254
  - chart: osh-infra/libvirt
    name: vbmc-libvirt
    namespace: openstack-vbmc
    values:
      network:
        backend: []
      labels:
        agent:
          libvirt:
            node_selector_key: virtualbmc
            node_selector_value: enabled
      conf:
        ceph:
          enabled: false
        libvirt:
          listen_addr: 0.0.0.0
      images:
        tags:
          dep_check: docker-kaas-local.artifactory.mirantis.com/openstack/extra/kubernetes-entrypoint:v1.0.0-20200311160233
          image_repo_sync: docker-kaas-local.artifactory.mirantis.com/openstack/extra/docker:17.07.0
          libvirt: docker-kaas-local.artifactory.mirantis.com/general/libvirt:4.0.0-bionic-20200409092635
      manifests:
        network_policy: false
      dependencies: {}
    version: 0.1.0-mcp-2254
  - chart: osh-infra/vbmc
    name: vbmc-virtualbmc
    namespace: openstack-vbmc
    values:
      images:
        tags:
          bootstrap: docker-kaas-local.artifactory.mirantis.com/openstack/heat:train-bionic-20200601180013
          vbmc_enroll_nodes: docker-kaas-local.artifactory.mirantis.com/openstack/heat:train-bionic-20200601180013
          activate_nodes: docker-kaas-local.artifactory.mirantis.com/openstack/heat:train-bionic-20200601180013
      endpoints:
        identity:
          namespace: openstack
          auth:
            admin:
              default_domain_id: default
              password: CHANGE_ME
              project_domain_name: default
              project_name: admin
              region_name: RegionOne
              user_domain_name: default
              username: admin
          host_fqdn_override:
            public:
              host: keystone.it.just.works
              tls:
                ca: CHANGE_ME
                crt: CHANGE_ME
                key: CHANGE_ME
          hosts:
            admin:
              host: keystone-api
            default: keystone
            internal: keystone-api
            public:
              host: keystone
              tls:
                ca: CHANGE_ME
                crt: CHANGE_ME
                key: CHANGE_ME
          port:
            api:
              admin: 5000
              default: 80
              internal: 5000
              public: 443
          scheme:
            default: http
            public: https
        cluster_domain_suffix: cluster.local
      manifests:
        network_policy: false
        job_activate_nodes: false
    version: 0.1.0-mcp-2254
  repositories:
  - name: osh-infra
    url: https://artifactory.mirantis.com/binary-kaas-local/openstack/helm/openstack-helm-infra
