apiVersion: lcm.mirantis.com/v1alpha1
kind: HelmBundle
metadata:
  name: openstack-virtualbmc
  namespace: openstack-vbmc
spec:
  releases:
  - chartURL: https://binary.mirantis.com/openstack/helm/openstack-helm-infra/libvirt-0.1.0-mcp-3094.tgz
    name: vbmc-libvirt
    namespace: openstack-vbmc
    values:
      network:
        backend: []
      labels:
        agent:
          libvirt:
            node_selector_key: virtualbmc
            node_selector_value: enabled
      conf:
        ceph:
          enabled: false
        libvirt:
          listen_addr: 0.0.0.0
      images:
        tags:
          dep_check: mirantis.azurecr.io/openstack/extra/kubernetes-entrypoint:v1.0.0-20200311160233
          image_repo_sync: mirantis.azurecr.io/openstack/extra/docker:17.07.0
          libvirt: mirantis.azurecr.io/general/libvirt:8.0.x-jammy-20240316092942
      manifests:
        network_policy: false
      dependencies: {}
    helmV3: true
  - chartURL: https://binary.mirantis.com/openstack/helm/openstack-helm-infra/vbmc-0.1.2+3141.tgz
    name: vbmc-virtualbmc
    namespace: openstack-vbmc
    values:
      images:
        tags:
          activate_nodes: mirantis.azurecr.io/openstack/heat:train-bionic-20200601180013
          bootstrap: mirantis.azurecr.io/openstack/heat:train-bionic-20200601180013
          sushy-tools: mirantis.azurecr.io/openstack/extra/vbmc:v0.2-20250923091859
          vbmc: mirantis.azurecr.io/openstack/extra/vbmc:v0.2-20250923091859
          vbmc_create_nodes: mirantis.azurecr.io/openstack/extra/vbmc:v0.2-20250923091859
          vbmc_enroll_nodes: mirantis.azurecr.io/openstack/heat:train-bionic-20200601180013
          openvswitch_db_server: mirantis.azurecr.io/general/openvswitch:3.3-noble-src-20250523053641
          openvswitch_vswitchd: mirantis.azurecr.io/general/openvswitch:3.3-noble-src-20250523053641
      endpoints:
        identity:
          namespace: openstack
          auth:
            admin:
              default_domain_id: default
              password: CHANGE_ME
              project_domain_name: default
              project_name: admin
              region_name: RegionOne
              user_domain_name: default
              username: admin
          host_fqdn_override:
            public:
              host: keystone.it.just.works
              tls:
                ca: CHANGE_ME
                crt: CHANGE_ME
                key: CHANGE_ME
          hosts:
            admin:
              host: keystone-api
            default: keystone
            internal: keystone-api
            public:
              host: keystone
              tls:
                ca: CHANGE_ME
                crt: CHANGE_ME
                key: CHANGE_ME
          port:
            api:
              admin: 5000
              default: 80
              internal: 5000
              public: 443
          scheme:
            default: http
            public: https
        cluster_domain_suffix: cluster.local
      conf:
        nodes:
          enabled: true
          node_interface: ens3
          deploy_kernel_image: ironic-agent.kernel
          deploy_ramdisk_image: ironic-agent.initramfs
          items:
            - driver: redfish
              properties:
                local_gb: 10
                cpus: 2
                memory_mb: 1024
                cpu_arch: x86_64
                capabilities: 'boot_mode:bios'
              resource_class: ram1024-cpus2-disk10
              driver_info:
                redfish_username: admin
                redfish_password: password
              network_interface: 'neutron'
              physnet: 'ironic'
              ports:
              - pxe_enabled: true
                portgroup_uuid: pg0
              - pxe_enabled: true
                portgroup_uuid: pg0
              portgroups:
              - name: pg0
                standalone_ports_supported: true
                mode: balance-rr
              boot_interface: redfish-virtual-media
            - driver: redfish
              properties:
                local_gb: 10
                cpus: 2
                memory_mb: 1024
                cpu_arch: x86_64
                capabilities: 'boot_mode:uefi'
              resource_class: ram1024-cpus2-disk10
              driver_info:
                redfish_username: admin
                redfish_password: password
              network_interface: 'neutron'
              physnet: 'ironic'
              ports:
              - pxe_enabled: true
                portgroup_uuid: pg0
              - pxe_enabled: true
                portgroup_uuid: pg0
              portgroups:
              - name: pg0
                standalone_ports_supported: true
                mode: balance-rr
              boot_interface: redfish-virtual-media
            - driver: redfish
              properties:
                local_gb: 10
                cpus: 2
                memory_mb: 1024
                cpu_arch: x86_64
                capabilities: 'boot_mode:uefi'
              resource_class: ram1024-cpus2-disk10
              driver_info:
                redfish_username: admin
                redfish_password: password
              network_interface: 'neutron'
              physnet: 'ironic'
              ports:
              - pxe_enabled: true
                portgroup_uuid: pg0
              - pxe_enabled: true
                portgroup_uuid: pg0
              portgroups:
              - name: pg0
                standalone_ports_supported: true
                mode: balance-rr
              boot_interface: redfish-https
      manifests:
        network_policy: false
        job_activate_nodes: false
        configmap_ssh: true
        secret_ca_bundle: true
        redfish_enabled: true
      network:
        sshd:
          enabled: true
    helmV3: true
