---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: nfs-server
  namespace: osh-system
spec:
  selector:
    matchLabels:
      app: nfs-server
  template:
    metadata:
      name: nfs-server
      labels:
        app: nfs-server
    spec:
      hostNetwork: true
      nodeSelector:
        openstack-compute-node: enabled
      initContainers:
        - command:
          - bash
          - -c
          - "set -ex; chroot /mnt/host-rootfs modprobe nfs; chroot /mnt/host-rootfs modprobe nfsd"
          image: mirantis.azurecr.io/openstack/extra/nfs-server:2.2.1
          imagePullPolicy: IfNotPresent
          name: init-kernel-modules
          resources: {}
          securityContext:
            privileged: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /mnt/host-rootfs
            name: host-rootfs
        - name: init-share-folders
          image: mirantis.azurecr.io/openstack/extra/nfs-server:2.2.1
          command:
            - mkdir
            - -p
            - /share/mariadb_backup_restore
            - /share/cinder_backup
            - /share/cinder_volume
          volumeMounts:
            - mountPath: /share
              name: nfs-vol
        - name: init-share-permissions
          image: mirantis.azurecr.io/openstack/extra/nfs-server:2.2.1
          command:
            - chown
            - -R
            - "42424:42424"
            - /share
          volumeMounts:
            - mountPath: /share
              name: nfs-vol
      containers:
        - name: nfs-server
          image: mirantis.azurecr.io/openstack/extra/nfs-server:2.2.1
          env:
            - name: NFS_EXPORT_0
              value: '/share  *(rw,sync,all_squash,no_subtree_check,anonuid=42424,anongid=42424,fsid=0)'
            - name: NFS_EXPORT_1
              value: '/share/mariadb_backup_restore  *(rw,sync)'
            - name: NFS_EXPORT_2
              value: '/share/cinder_backup  *(rw,sync)'
            - name: NFS_EXPORT_3
              value: '/share/cinder_volume  *(rw,sync)'
            - name: NFS_LOG_LEVEL
              value: DEBUG
          volumeMounts:
            - mountPath: /share
              name: nfs-vol
            - mountPath: /lib/modules
              name: libmodules
          securityContext:
            privileged: true
      volumes:
        - name: host-rootfs
          hostPath:
            path: /
            type: ""
        - name: nfs-vol
          hostPath:
            path: /var/lib/nfs-share
            type: DirectoryOrCreate
        - name: libmodules
          hostPath:
            path: /lib/modules
            type: ""
