apiVersion: lcm.mirantis.com/v1alpha1
kind: MiraCeph
metadata:
  name: cephcluster
  namespace: ceph-lcm-mirantis
spec:
  network:
    hostNetwork: true
    clusterNet: 10.11.0.0/24
    publicNet: 10.12.0.0/24
  version: 14.2.9
  dashboardEnabled: false
  failureDomain: host
  pools:
    - deviceClass: hdd
      role: kubernetes
      name: mirablock-k8s-block
      default: true
      replicated:
        size: 2
    - deviceClass: hdd
      role: volumes
      name: volumes
      replicated:
        size: 2
    - deviceClass: hdd
      role: vms
      name: vms
      replicated:
        size: 2
    - deviceClass: hdd
      role: backup
      name: backup
      replicated:
        size: 2
    - deviceClass: hdd
      role: images
      name: images
      replicated:
        size: 2
    - deviceClass: hdd
      role: other
      name: other
      replicated:
        size: 2
  nodes:
    - name: Values.CHANGE_ME_node1_name
      devices:
        - name: sdb
          config:
            deviceClass: hdd
      roles: [mon, mgr]
      crushPath:
    - name: Values.CHANGE_ME_node2_name
      devices:
        - name: sdb
          config:
            deviceClass: hdd
      roles: [mon, mgr]
      crushPath:
    - name: Values.CHANGE_ME_node3_name
      devices:
        - name: sdb
          config:
            deviceClass: hdd
      roles: [mon, mgr]
