apiVersion: lcm.mirantis.com/v1alpha1
kind: CephDeployment
metadata:
  name: cephcluster
  namespace: ceph-lcm-mirantis
spec:
  blockStorage:
    pools:
    - name: mirablock-k8s-block
      role: kubernetes
      storageClassOpts:
        default: true
      spec:
        deviceClass: hdd
        replicated:
          size: 1
    - name: volumes
      role: volumes
      spec:
        deviceClass: hdd
        replicated:
          size: 1
    - name: vms
      role: vms
      spec:
        deviceClass: hdd
        replicated:
          size: 1
    - name: backup
      role: backup
      spec:
        deviceClass: hdd
        replicated:
          size: 1
    - name: images
      role: images
      spec:
        deviceClass: hdd
        replicated:
          size: 1
  cluster:
    dashboard:
      enabled: false
    network:
      addressRanges:
        cluster: ["10.11.0.0/24"]
        public: ["10.12.0.0/24"]
    placement:
      osd:
        tolerations:
          - key: "com.docker.ucp.manager"
            operator: "Exists"
            effect: "NoSchedule"
  nodes:
    - name: Values.CHANGE_ME_node1_name
      devices:
        - name: sdb
          config:
            deviceClass: hdd
      roles: [mon, mgr]
  objectStorage:
    objectStores:
      - name: openstack-store
        # w/a until moved to envoy
        usedByRockoon: true
        spec:
          dataPool:
            deviceClass: hdd
            failureDomain: host
            replicated:
              size: 1
          gateway:
            instances: 1
            port: 80
            securePort: 8443
          metadataPool:
            deviceClass: hdd
            failureDomain: host
            replicated:
              size: 1
          preservePoolsOnDelete: false
  rookConfig:
    osd_pool_default_size: "1"
