apiVersion: lcm.mirantis.com/v1alpha1
kind: CephDeployment
metadata:
  name: cephcluster
  namespace: ceph-lcm-mirantis
spec:
  rookConfig:
    # IMPORTANT: for production change to 3 or remove.
    osd_pool_default_size: "2"
  network:
    clusterNet: 10.11.0.0/24
    publicNet: 10.12.0.0/24
  dashboard: false
  pools:
    - deviceClass: hdd
      role: kubernetes
      name: mirablock-k8s-block
      storageClassOpts:
        default: true
      replicated:
        size: 2
    - deviceClass: hdd
      role: volumes
      name: volumes
      replicated:
        size: 2
    - deviceClass: hdd
      role: vms
      name: vms
      replicated:
        size: 2
    - deviceClass: hdd
      role: backup
      name: backup
      replicated:
        size: 2
    - deviceClass: hdd
      role: images
      name: images
      replicated:
        size: 2
  objectStorage:
    rgw:
      name: openstack-store
      metadataPool:
        failureDomain: host
        deviceClass: hdd
        replicated:
          size: 2
      dataPool:
        deviceClass: hdd
        failureDomain: host
        replicated:
          size: 2
      gateway:
        # NOTE(vsaienko): rgw do not have synchronization, use 1 replica
        # to avoid races in tests.
        instances: 1
        allNodes: false
        port: 80
        securePort: 8443
      preservePoolsOnDelete: false
  nodes:
    - name: Values.CHANGE_ME_node1_name
      devices:
        - name: sdb
          config:
            deviceClass: hdd
      roles: [mon, mgr]
    - name: Values.CHANGE_ME_node2_name
      devices:
        - name: sdb
          config:
            deviceClass: hdd
      roles: [mon, mgr]
    - name: Values.CHANGE_ME_node3_name
      devices:
        - name: sdb
          config:
            deviceClass: hdd
      roles: [mon, mgr]
