---
apiVersion: v1
kind: Namespace
metadata:
  name: stacklight
---
apiVersion: lcm.mirantis.com/v1alpha1
kind: HelmBundle
metadata:
  name: stacklight
  namespace: stacklight
spec:
  repositories:
  - name: stacklight
    url: https://binary.mirantis.com/stacklight/helm
  releases:
  - name: stacklight
    chart: stacklight/stacklight
    version: 0.1.2-mcp-492
    namespace: stacklight
    values:
      clusterSize: small
      global:
        dockerBaseUrl: mirantis.azurecr.io
        helmBaseUrl: https://binary.mirantis.com
      createHelmBundleCRD: false
      deployController: false
      highAvailabilityEnabled: true
      nginxExporter:
        enabled: false
      openstack:
        enabled: true
      tungstenFabricMonitoring:
        enabled: false
      ceph:
        enabled: true
      calico:
        enabled: false
      nodeSelector:
        default:
          role: stacklight
          stacklight: enabled
      platform: ucp
      storage:
        componentStorageClasses:
          elasticsearch: "lvp-fake-root"
          postgresql: "lvp-fake-root"
          prometheusAlertManager: "lvp-fake-root"
          prometheusServer: "lvp-fake-root"
