---
apiVersion: v1
kind: Namespace
metadata:
  name: stacklight
---
apiVersion: lcm.mirantis.com/v1alpha1
kind: HelmBundle
metadata:
  name: stacklight
  namespace: stacklight
spec:
  releases:
  - name: stacklight
    helmV3: true
    chartURL: https://binary.mirantis.com/stacklight/helm/stacklight-0.13.2.tgz
    version: 0.13.2
    namespace: stacklight
    values:
      clusterSize: small
      global:
        dockerBaseUrl: mirantis.azurecr.io
        helmBaseUrl: https://binary.mirantis.com
      createHelmBundleCRD: false
      exposeLoadBalancers: true
      helmController:
        enabled: false
      highAvailabilityEnabled: true
      openstack:
        enabled: true
        cloudprober:
          enabled: true
      tungstenFabricMonitoring:
        enabled: false
      ceph:
        enabled: true
      calico:
        enabled: false
      nodeSelector:
        default:
          role: stacklight
          stacklight: enabled
      platform: ucp
      storage:
        componentStorageClasses:
          elasticsearch: "lvp-fake-root"
          postgresql: "lvp-fake-root"
          prometheusAlertManager: "lvp-fake-root"
          prometheusServer: "lvp-fake-root"
