---
apiVersion: v1
kind: Namespace
metadata:
  name: stacklight
---
apiVersion: lcm.mirantis.com/v1alpha1
kind: HelmBundle
metadata:
  name: stacklight
  namespace: stacklight
spec:
  repositories:
  - name: stacklight
    url: https://artifactory.mirantis.com/binary-kaas-local/stacklight/helm
  releases:
  - name: stacklight
    chart: stacklight/stacklight
    version: 0.1.2-mcp-124
    namespace: stacklight
    values:
      global:
        dockerBaseUrl: docker-kaas-local.artifactory.mirantis.com
        helmBaseUrl: https://artifactory.mirantis.com/binary-kaas-local
      createHelmBundleCRD: false
      deployController: false
      highAvailabilityEnabled: true
      nginxExporter:
        enabled: false
      openstack:
        enabled: true
      ceph:
        enabled: true
      calico:
        enabled: false
      nodeSelector:
        default:
          role: stacklight
          stacklight: enabled
      platform: ucp
      storage:
        componentStorageClasses:
          elasticsearch: "lvp-fake-root"
          prometheusServer: "lvp-fake-root"
