apiVersion: operator.tf.mirantis.com/v1alpha1
kind: TFOperator
metadata:
  name: openstack-tf
  namespace: tf
spec:
  settings:
    orchestrator: openstack
  controllers:
    cassandra:
      deployments:
        - name: tf-cassandra-analytics
          dataCapacity: 20Gi