apiVersion: operator.tf.mirantis.com/v1alpha1
kind: TFOperator
metadata:
  name: openstack-tf
  namespace: tf
spec:
  settings:
    orchestrator: openstack
    osSharedNamespace: openstack-tf-shared
    osSecret: tf-data
