apiVersion: lcm.mirantis.com/v1alpha1
kind: HelmBundle
metadata:
  name: tungstenfabric-operator
  namespace: tf
spec:
  repositories:
  - name: tf
    url: https://binary.mirantis.com/tungsten/helm
  releases:
  - chart: tf/tungstenfabric-operator
    name: tungstenfabric-operator
    version: 0.19.0
    namespace: tf
    helmV3: true
    values:
      global:
        dockerBaseUrl: mirantis.azurecr.io
