apiVersion: lcm.mirantis.com/v1alpha1
kind: OpenStackDeployment
metadata:
  name: osh-dev
  namespace: openstack
  labels: {}
  annotations: {}
spec:
  openstack_version: victoria
  preset: compute
  size: single
  internal_domain_name: cluster.local
  public_domain_name: it.just.works
  local_volume_storage_class: lvp-fake-root
  persistent_volume_storage_class: mirablock-k8s-block-hdd
  features:
    ssl:
      public_endpoints:
        api_cert: |-
          # Update server certificate content
        api_key: |-
          # Update server private key content
        ca_cert: |-
          # Update CA certificate content
    neutron:
      tunnel_interface: ens3
      external_networks:
        - physnet: physnet1
          interface: veth-phy
          bridge: br-ex
          network_types:
           - flat
          vlan_ranges: null
          mtu: null
      floating_network:
        enabled: True
        physnet: physnet1
        subnet:
          range: 10.11.12.0/24
          pool_start: 10.11.12.100
          pool_end: 10.11.12.200
          gateway: 10.11.12.11
    nova:
      console:
        novnc:
          tls:
            enabled: true
      live_migration_interface: ens3
      libvirt:
        tls:
          enabled: true
      images:
        backend: ceph
    messaging:
      notifications:
        external:
          enabled: true
          topics:
          - external-consumer-A
          # TODO(vsaienko): enable when 34580 is fixed
          # - external-consumer-b
          - ec-a
          - ec-A
  # enabled services and their specific configuration
  services:
    # TODO(vsaienko): remove when openstack-controller fixed.
    memcached:
      memcached:
        values:
          pod:
            replicas:
              server: 1
    networking:
      neutron:
        values:
          conf:
            neutron:
              DEFAULT:
                global_physnet_mtu: 1480
    orchestration:
      heat:
        values:
          conf:
            heat:
              clients_heat:
                insecure: true
