apiVersion: lcm.mirantis.com/v1alpha1
kind: OpenStackDeployment
metadata:
  name: osh-dev
  namespace: openstack
  labels: {}
  annotations: {}
spec:
  draft: false
  openstack_version: ussuri
  preset: compute
  size: tiny
  internal_domain_name: cluster.local
  public_domain_name: it.just.works
  local_volume_storage_class: lvp-fake-root
  persistent_volume_storage_class: mirablock-k8s-block-hdd
  artifacts:
    images_base_url: mirantis.azurecr.io
    binary_base_url: https://binary.mirantis.com
  features:
    services:
      - key-manager
      - baremetal
    ssl:
      public_endpoints:
        api_cert: |-
          # Update server certificate content
        api_key: |-
          # Update server private key content
        ca_cert: |-
          # Update CA certificate content
    neutron:
      tunnel_interface: ens3
      tenant_network_types:
        - vlan
      external_networks:
        - physnet: physnet1
          interface: veth-phy
          bridge: br-ex
          network_types:
            - flat
          vlan_ranges: null
          mtu: null
        - physnet: ironic
          interface: veth-bm
          bridge: ironic-pxe
          network_types:
            - vlan
          vlan_ranges: 1000:1099
      floating_network:
        enabled: True
        physnet: physnet1
        subnet:
          range: 10.11.12.0/24
          pool_start: 10.11.12.100
          pool_end: 10.11.12.200
          gateway: 10.11.12.11
    ironic:
      provisioning_interface: pxe.1000
      baremetal_network_name: ironic-provisioning
      networks:
        baremetal:
          physnet: ironic
          name: ironic-provisioning
          network_type: vlan
          segmentation_id: 1000
          external: true
          shared: false
          subnets:
            - name: baremetal-subnet
              range: 10.13.0.0/24
              pool_start: 10.13.0.100
              pool_end: 10.13.0.254
              gateway: 10.13.0.11
      agent_images:
        base_url: https://binary.mirantis.com/openstack/bin/ironic/tinyipa
        initramfs: tinyipa-stable-ussuri-20201008064914.gz
        kernel: tinyipa-stable-ussuri-20201008064914.vmlinuz
    nova:
      live_migration_interface: ens3
      images:
        backend: local
    stacklight:
      user:
        password: stacklight
  # enabled services and their specific configuration
  services:
    # NOTE(vsaienko): run on all nodes to have access to public API from routers/VMs
    # For more details please see https://mirantis.jira.com/browse/PRODX-1321
    ingress:
      ingress:
        values:
          labels:
            server:
              node_selector_key: kubernetes.io/os
              node_selector_value: linux
    networking:
      neutron:
        values:
          conf:
            neutron:
              DEFAULT:
                # to match Calico tunnel value within container operations
                global_physnet_mtu: 1480
    orchestration:
      heat:
        values:
          conf:
            heat:
              clients_heat:
                insecure: true
