apiVersion: lcm.mirantis.com/v1alpha1
kind: OpenStackDeployment
metadata:
  name: osh-dev
  namespace: openstack
  labels: {}
  annotations: {}
spec:
  draft: false
  openstack_version: train
  profile: compute
  size: tiny
  internal_domain_name: cluster.local
  public_domain_name: it.just.works
  artifacts:
    images_base_url: docker-kaas-local.artifactory.mirantis.com
    binary_base_url: https://binary.mirantis.com
  features:
    services:
     - key-manager
    ssl:
      public_endpoints:
        api_cert: |-
          # Update server certificate content
        api_key: |-
          # Update server private key content
        ca_cert: |-
          # Update CA certificate content
    neutron:
      tunnel_interface: ens3
      external_networks:
        - physnet: physnet1
          interface: veth-phy
          bridge: br-ex
          network_types:
           - flat
          vlan_ranges: null
          mtu: null
      floating_network:
        enabled: True
        physnet: physnet1
        subnet:
          range: 10.11.12.0/24
          pool_start: 10.11.12.100
          pool_end: 10.11.12.200
          gateway: 10.11.12.11
    nova:
      live_migration_interface: ens3
      images:
        backend: local
    stacklight:
      user:
        password: stacklight
  # enabled services and their specific configuration
  services:
    # NOTE(vsaienko): run on all nodes to have access to public API from routers/VMs
    # For more details please see https://mirantis.jira.com/browse/PRODX-1321
    ingress:
      ingress:
        values:
          labels:
            server:
              node_selector_key: kubernetes.io/os
              node_selector_value: linux
    # TODO(vsaienko): move to features level when 0.1.9 available
    load-balancer:
      octavia:
        values:
          octavia:
            settings:
              lbmgmt_cidr: "10.255.0.0/16"
              lbmgmt_subnet_start: "10.255.1.0"
              lbmgmt_subnet_end: "10.255.255.254"
    networking:
      neutron:
        values:
          conf:
            neutron:
              DEFAULT:
                # to match Calico tunnel value within container operations
                global_physnet_mtu: 1480
    orchestration:
      heat:
        values:
          conf:
            heat:
              clients_heat:
                insecure: true
