apiVersion: lcm.mirantis.com/v1alpha1
kind: OpenStackDeployment
metadata:
  name: osh-dev
  namespace: openstack
  labels: {}
  annotations: {}
spec:
  openstack_version: antelope
  preset: compute
  size: tiny
  internal_domain_name: cluster.local
  public_domain_name: it.just.works
  features:
    services:
      - cloudprober
      - shared-file-system
    ssl:
      public_endpoints:
        api_cert: |-
          # Update server certificate content
        api_key: |-
          # Update server private key content
        ca_cert: |-
          # Update CA certificate content
    manila:
      share:
        backends:
          cephfs:
            type: statefulset
            values:
              conf:
                manila:
                  DEFAULT:
                    enabled_share_backends: cephfsnative
                  cephfsnative:
                    share_backend_name: cephfsnative
                    share_driver: manila.share.drivers.cephfs.driver.CephFSDriver
    neutron:
      tunnel_interface: ens3
      external_networks:
        - physnet: physnet1
          interface: veth-phy
          bridge: br-ex
          network_types:
           - flat
          vlan_ranges: null
          mtu: null
      floating_network:
        enabled: True
        physnet: physnet1
        subnet:
          range: 10.11.12.0/24
          pool_start: 10.11.12.100
          pool_end: 10.11.12.200
          gateway: 10.11.12.11
    nova:
      console:
        spice:
          enabled: true
        novnc:
          tls:
            enabled: true
      live_migration_interface: ens3
      libvirt:
        tls:
          enabled: true
      images:
        backend: raw
    messaging:
      notifications:
        external:
          enabled: true
          topics:
          - external-consumer-A
          # TODO(vsaienko): enable when 34580 is fixed
          # - external-consumer-b
          - ec-a
          - ec-A
  # enabled services and their specific configuration
  services:
    networking:
      neutron:
        values:
          conf:
            neutron:
              DEFAULT:
                global_physnet_mtu: 1480
    orchestration:
      heat:
        values:
          conf:
            heat:
              clients_heat:
                insecure: true
    shared-file-system:
      manila:
        values:
          conf:
            manila:
              DEFAULT:
                # NOTE: change default share type to let tempest
                # always use cephfs backend
                default_share_type: cephfsnative
    tempest:
      tempest:
        values:
          conf:
            tempest:
              share:
                # cephfs is dhss false driver, multitenancy not supported
                multitenancy_enabled: false
                # NOTE(mkarpin): Do not run all share group tests till find a way to not run
                #                only group tests which require snapshots
                run_share_group_tests: false
                # some tests require share type creation with proper protocol set
                capability_storage_protocol: CEPHFS
