apiVersion: lcm.mirantis.com/v1alpha1
kind: OpenStackDeployment
metadata:
  name: osh-dev
  namespace: openstack
  labels: {}
  annotations: {}
spec:
  openstack_version: ussuri
  preset: compute
  size: tiny
  public_domain_name: it.just.works
  features:
    ssl:
      public_endpoints:
        api_cert: |-
          # Update server certificate content
        api_key: |-
          # Update server private key content
        ca_cert: |-
          # Update CA certificate content
    neutron:
      tunnel_interface: ens3
      external_networks:
        - physnet: physnet1
          interface: veth-phy
          bridge: br-ex
          network_types:
           - flat
          vlan_ranges: null
          mtu: null
      floating_network:
        enabled: True
        physnet: physnet1
        subnet:
          range: 10.11.12.0/24
          pool_start: 10.11.12.100
          pool_end: 10.11.12.200
          gateway: 10.11.12.11
    nova:
      live_migration_interface: ens3
      images:
        backend: local
    stacklight:
      user:
        password: stacklight
  # enabled services and their specific configuration
  services:
    networking:
      neutron:
        values:
          conf:
            neutron:
              DEFAULT:
                global_physnet_mtu: 1480
    orchestration:
      heat:
        values:
          conf:
            heat:
              clients_heat:
                insecure: true
    block-storage:
      cinder:
        values:
          bootstrap:
            volume_types:
              netapp:
                volume_backend_name: netapp
          conf:
            cinder:
              DEFAULT:
                default_volume_type: netapp
            standalone_backends:
              statefulsets:
                netapp:
                  conf:
                    DEFAULT:
                      cluster: ""
                      enabled_backends: netapp
                    netapp:
                      netapp_login: changeme
                      netapp_password: changeme
                      netapp_server_hostname: changeme
                      netapp_server_port: 80
                      netapp_storage_family: ontap_cluster
                      netapp_storage_protocol: iscsi
                      netapp_vserver: cinder
                      volume_backend_name: netapp
                      volume_driver: cinder.volume.drivers.netapp.common.NetAppDriver
          pod:
            security_context:
              cinder_volume:
                container:
                  cinder_volume:
                    readOnlyRootFilesystem: false
                    runAsUser: 0
            useHostNetwork:
              volume: true
