---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: helmbundles.lcm.mirantis.com
spec:
  group: lcm.mirantis.com
  names:
    kind: HelmBundle
    listKind: HelmBundleList
    plural: helmbundles
    singular: helmbundle
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: HelmBundle specifies several Helm releases to be installed
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: HelmBundleSpec describes a set of Helm releases and repositories that they use.
            properties:
              release:
                description: Release version of controller that is allowed to process this bundle.
                type: string
              releases:
                description: The list of releases in this bundle.
                items:
                  description: HelmReleaseSpec specifies a Helm release.
                  properties:
                    chart:
                      description: Chart name of the form "repo/name" or just "name".
                      type: string
                    chartURL:
                      description: Direct URL to the chart's tarball
                      type: string
                    helmV3:
                      description: HelmV3 specifies whether Helm v3 should be used. Defaults to v2.
                      type: boolean
                    labels:
                      additionalProperties:
                        type: string
                      description: The labels to apply to the release.
                      type: object
                    name:
                      description: The name of this release.
                      type: string
                    namespace:
                      description: The namespace of this release.
                      type: string
                    requires:
                      description: List of releases that must be installed and ready in order for this release to be installed
                      items:
                        type: string
                      type: array
                    values:
                      description: Values used for parametrization of the chart.
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                    version:
                      description: Chart version.
                      type: string
                  required:
                  - name
                  - namespace
                  type: object
                type: array
              repositories:
                description: The list of repositories used by this bundle.
                items:
                  description: HelmRepositorySpec describes a repository used by a HelmBundle.
                  properties:
                    authSecret:
                      description: Authentication secret name.
                      type: string
                    name:
                      description: The name of the repository.
                      type: string
                    url:
                      description: The URL of the repository.
                      type: string
                  required:
                  - name
                  - url
                  type: object
                type: array
            required:
            - releases
            type: object
          status:
            description: HelmBundleStatus describes a status of a HelmBundle.
            properties:
              observedGeneration:
                format: int64
                type: integer
              release:
                description: Release version of controller that processed this bundle.
                type: string
              releaseStatuses:
                additionalProperties:
                  description: HelmReleaseStatus describes a status of a release.
                  properties:
                    attempt:
                      description: Attempt is a number of installs
                      type: integer
                    chart:
                      description: Chart name of the form "repo/name" or just "name".
                      type: string
                    finishedAt:
                      description: LastUpdateTime is a time of last try to install
                      format: date-time
                      type: string
                    hash:
                      description: The hash of the parametrization values.
                      type: string
                    helmV3:
                      description: HelmV3 indicates whether the release was installed with Helm v3.
                      type: boolean
                    message:
                      description: Error message in case if the release installation failed.
                      type: string
                    namespace:
                      description: Namespace of the release.
                      type: string
                    notes:
                      description: Notes contain the rendered notes for this release.
                      type: string
                    ready:
                      description: Reflects readiness of the release
                      type: boolean
                    revision:
                      description: Revision of the release.
                      type: integer
                    status:
                      description: Status of the release
                      type: string
                    success:
                      description: True if the release was installed successfully. deprecated, use Status
                      type: boolean
                    version:
                      description: Chart version.
                      type: string
                  required:
                  - chart
                  - hash
                  - notes
                  - status
                  - success
                  - version
                  type: object
                description: The mapping of the names of the releases to their statuses.
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
