---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-admin-mosk
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: helm-controller-mosk
  namespace: osh-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin-mosk
subjects:
- kind: ServiceAccount
  name: helm-controller-mosk
  namespace: osh-system
---
apiVersion: v1
kind: Service
metadata:
  name: helm-controller-service
  namespace: osh-system
  labels:
    app: helm-controller
spec:
  selector:
    app: helm-controller
  ports:
  # tiller probe/metrics port
  - port: 44135
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: helm-controller-mosk
  namespace: osh-system
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: helm-controller
  name: helm-controller
  namespace: osh-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helm-controller
  serviceName: helm-controller-service
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  template:
    metadata:
      labels:
        app: helm-controller
    spec:
      serviceAccountName: helm-controller-mosk
      containers:
      - name: controller
        command: ["/bin/controller"]
        env:
        - name: TMPDIR
          value: /helm
        - name: HELM_CONTROLLER_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: HELM_CONTROLLER_NODE_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        image: mirantis.azurecr.io/core/helm-controller:1.41.2
        securityContext:
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: home
          mountPath: /helm
      volumes:
      - name: home
        emptyDir: {}