apiVersion: lcm.mirantis.com/v1alpha1
kind: HelmBundle
metadata:
  name: ceph-operator
  namespace: osh-system
spec:
  releases:
  - chart: ceph/ceph-operator
    chartURL: https://binary.mirantis.com/ceph/helm/ceph-operator-1.0.0-mcc-2.29.0-7.tgz
    name: ceph-operator
    helmV3: true
    namespace: osh-system
    values:
      global:
        dockerBaseUrl: mirantis.azurecr.io
      rookOperatorPlacement:
        nodeSelector:
          openstack-control-plane: enabled
