apiVersion: lcm.mirantis.com/v1alpha1
kind: HelmBundle
metadata:
  name: ceph-operator
  namespace: osh-system
spec:
  repositories:
  - name: ceph
    url: https://binary.mirantis.com/ceph/helm/
  releases:
  - chart: ceph/ceph-operator
    name: ceph-operator
    version: 1.0.0-mcp-44
    namespace: osh-system
    values:
      global:
        dockerBaseUrl: mirantis.azurecr.io
      images:
        cephController:
          repository: ceph/mcp/ceph-controller
          tag: v1.0.0-20201110171443
