apiVersion: lcm.mirantis.com/v1alpha1
kind: HelmBundle
metadata:
  name: ceph-operator
  namespace: osh-system
spec:
  repositories:
  - name: ceph
    url: https://binary.mirantis.com/ceph/helm/
  releases:
  - chart: ceph/ceph-operator
    name: ceph-operator
    version: 1.0.0-mcp-606
    namespace: osh-system
    values:
      global:
        dockerBaseUrl: mirantis.azurecr.io
      waitForOpenstackLock: "true"
