apiVersion: lcm.mirantis.com/v1alpha1
kind: HelmBundle
metadata:
  name: ceph-operator
  namespace: osh-system
spec:
  repositories:
  - name: ceph
    url: https://binary.mirantis.com/ceph/helm/
  releases:
  - chart: ceph/ceph-operator
    name: ceph-operator
    version: 1.0.0-mcc-2.26.5-1
    helmV3: true
    namespace: osh-system
    values:
      global:
        dockerBaseUrl: mirantis.azurecr.io
      rookOperatorPlacement:
        nodeSelector:
          openstack-control-plane: enabled
