apiVersion: lcm.mirantis.com/v1alpha1
kind: HelmBundle
metadata:
  name: ceph-operator
  namespace: osh-system
spec:
  repositories:
  - name: ceph
    url: https://artifactory.mirantis.com/binary-kaas-local/ceph/helm/
  releases:
  - chart: ceph/ceph-operator
    name: ceph-operator
    version: 1.0.0-mcp-18
    namespace: osh-system
    values:
      global:
        dockerBaseUrl: docker-kaas-local.artifactory.mirantis.com
      images:
        cephController:
          repository: ceph/mcp/ceph-controller
          tag: v1.0.0-20200826102223
