apiVersion: lcm.mirantis.com/v1alpha1
kind: HelmBundle
metadata:
  name: ceph-operator
  namespace: osh-system
spec:
  repositories:
  - name: ceph
    url: https://binary.mirantis.com/ceph/helm/
  releases:
  - chart: ceph/ceph-operator
    name: ceph-operator
    version: 1.0.0-mcp-271
    namespace: osh-system
    values:
      global:
        dockerBaseUrl: mirantis.azurecr.io
      # TODO(vsaienko): remove when fixed PRODX-15052
      hyperconverge:
        tolerations:
          osd: |
            - effect: NoSchedule
              key: com.docker.ucp.manager
              operator: Exists
