apiVersion: lcm.mirantis.com/v1alpha1
kind: HelmBundle
metadata:
  name: openstack-operator
  namespace: osh-system
spec:
  repositories:
  - name: openstack-controller
    url: https://binary.mirantis.com/openstack/helm/openstack-controller
  releases:
  - name: openstack-operator
    chart: openstack-controller/openstack-operator
    version: 0.7.5
    namespace: osh-system
    values:
      global:
        dockerBaseUrl: mirantis.azurecr.io
        helmBaseUrl: https://binary.mirantis.com
      image:
        tag: 0.7.5
      # The kopf peering object will be created by ceph controller.
      kopf:
        enabled: false
      osdpl:
        settings:
          helm2to3:
            raw:
              TILLER_NAMESPACE: osh-system
