apiVersion: lcm.mirantis.com/v1alpha1
kind: HelmBundle
metadata:
  name: redis-operator
  namespace: osh-system
spec:
  repositories:
  - name: hub_stable
    url: https://binary.mirantis.com/openstack/helm/redis-operator
  releases:
  - name: os-redis-operator
    chart: hub_stable/redis-operator
    helmV3: true
    version: 3.2.8-mcp-9
    namespace: openstack-redis
    values:
      global:
        dockerBaseUrl: mirantis.azurecr.io
      image:
        name: redis-operator
        repository: openstack/extra
        tag: v1.2.4-20231107105540
      rbac:
        apiVersion: v1
        install: true
      node_affinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: openstack-control-plane
              operator: In
              values:
              - enabled
