---
apiVersion: lcm.mirantis.com/v1alpha1
kind: HelmBundle
metadata:
  name: metallb
  namespace: osh-system
spec:
  releases:
  - chart: kaas/metallb-crds
    chartURL: https://binary.mirantis.com/core/helm/metallb-crds-1.37.20.tgz
    helmV3: true
    name: metallb-crds
    namespace: metallb
    values: {}
    version: 1.37.20
  - chart: kaas/metallb
    chartURL: https://binary.mirantis.com/core/helm/metallb-1.37.20.tgz
    helmV3: true
    name: metallb
    namespace: metallb
    requires:
    - metallb-crds
    values: {}
    version: 1.37.20
