---
apiVersion: lcm.mirantis.com/v1alpha1
kind: HelmBundle
metadata:
  name: metallb
  namespace: osh-system
spec:
  releases:
  - chart: kaas/metallb-crds
    chartURL: https://binary.mirantis.com/core/helm/metallb-crds-1.37.20.tgz
    helmV3: true
    name: metallb-crds
    namespace: metallb
    values: {}
    version: 1.37.20
  - chart: kaas/metallb
    chartURL: https://binary.mirantis.com/core/helm/metallb-1.37.20.tgz
    helmV3: true
    name: metallb
    namespace: metallb
    requires:
    - metallb-crds
    values: {}
    version: 1.37.20
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  creationTimestamp: null
  name: openstack-default
  namespace: metallb
spec:
  addresses:
  - 10.172.1.100-10.172.1.255
  autoAssign: true
  avoidBuggyIPs: true
status: {}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  creationTimestamp: null
  name: l2advertisement1
  namespace: metallb
spec:
  ipAddressPools:
  - openstack-default
status: {}
