apiVersion: lcm.mirantis.com/v1alpha1
kind: HelmBundle
metadata:
  name: etcd-vault
  namespace: osh-system
spec:
  repositories:
  - name: osh-infra
    url: https://artifactory.mirantis.com/binary-kaas-local/openstack/helm/openstack-helm-infra
  releases:
  - name: etcd-vault
    chart: osh-infra/etcd
    version: 0.1.0-mcp-2240
    namespace: openstack-vault
    values:
      images:
        tags:
          etcd: docker-kaas-local.artifactory.mirantis.com/openstack/extra/etcd:3.2.26
          dep_check: docker-kaas-local.artifactory.mirantis.com/openstack/extra/kubernetes-entrypoint:v1.0.0-20200311160233
          image_repo_sync: docker-kaas-local.artifactory.mirantis.com/openstack/extra/docker:17.07.0
      pod:
        replicas:
          etcd: 3
      volume:
        class_name: lvp-fake-root
